In [1]:
import numpy as np
import EQTransformer as eqt
from EQTransformer.core.trainer import trainer
# np.array([1, 2, 3, 4, 5])
# dir(EQTransformer)
# print(eqt.__version__)
trainer(input_hdf5='test.hdf5', input_csv='training_PandS_up.csv', output_name='test_trainer_up', cnn_blocks=2, lstm_blocks=1, padding='same', activation='relu', drop_rate=0.2, label_type='gaussian', add_event_r=0.6, add_gap_r=0.2, shift_event_r=0.9, add_noise_r=0.5, mode='generator', train_valid_test_split=[0.60, 0.20, 0.20], batch_size=20, epochs=10, patience=2, gpuid=None, gpu_limit=None, input_dimention=(6000, 3))
# trainer(input_hdf5='/Users/jun/phasepick/EQTransformer/ModelsAndSampleData/100samples.hdf5',
#         input_csv='/Users/jun/phasepick/EQTransformer/ModelsAndSampleData/100samples.csv',
#         output_name='test_trainer',                
#         cnn_blocks=2,
#         lstm_blocks=1,
#         padding='same',
#         activation='relu',
#         drop_rate=0.2,
#         label_type='gaussian',
#         add_event_r=0.6,
#         add_gap_r=0.2,
#         shift_event_r=0.9,
#         add_noise_r=0.5, 
#         mode='generator',
#         train_valid_test_split=[0.60, 0.20, 0.20],
#         batch_size=20,
#         epochs=10, 
#         patience=2,
#         gpuid=None,
#         gpu_limit=None)


Using TensorFlow backend.
2023-04-25 14:30:44.499063: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-04-25 14:30:44.530119: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fee8b4df2f0 executing computations on platform Host. Devices:
2023-04-25 14:30:44.530134: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version


Learning rate:  0.001
Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input (InputLayer)              (None, 6000, 3)      0                                            
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 6000, 8)      272         input[0][0]                      
__________________________________________________________________________________________________
max_pooling1d_1 (MaxPooling1D)  (None, 3000, 8)      0           conv1d_1[0][0]                   
__________________________________________________________________________________________________
conv1d_2 (Conv1D)               (None, 3000, 16)     1168        max_pooling1d_1[0][0]            
______________________________________________________________________

2023-04-25 14:31:51.853279: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-04-25 14:31:52.307116: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-04-25 14:31:53.005826: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] model_pruner failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss/detector_loss/binary_crossentropy/weighted_loss/concat' has self cycle fanin 'loss/detector_loss/binary_crossentropy/weighted_loss/concat'.
2023-04-25 14:31:53.599791: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss/detector_loss/binary_crossentropy/weighted_loss/concat' has self cycle fanin 'loss/detector_loss/binary_

3585/3586 [============================>.] - ETA: 0s - loss: 0.0315 - detector_loss: 0.2833 - picker_P_loss: 0.0141 - picker_S_loss: 0.0195 - detector_f1: 0.7993 - picker_P_f1: 0.1599 - picker_S_f1: 3.0882e-04

2023-04-25 14:59:32.605449: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-04-25 14:59:32.630058: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2023-04-25 14:59:32.696582: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] model_pruner failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss/detector_loss/binary_crossentropy/weighted_loss/concat' has self cycle fanin 'loss/detector_loss/binary_crossentropy/weighted_loss/concat'.
2023-04-25 14:59:32.789336: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'loss/detector_loss/binary_crossentropy/weighted_loss/concat' has self cycle fanin 'loss/detector_loss/binary_

3586/3586 [==============================] - 1759s 490ms/step - loss: 0.0314 - detector_loss: 0.2832 - picker_P_loss: 0.0141 - picker_S_loss: 0.0195 - detector_f1: 0.7993 - picker_P_f1: 0.1600 - picker_S_f1: 3.0874e-04 - val_loss: 0.0216 - val_detector_loss: 0.1466 - val_picker_P_loss: 0.0065 - val_picker_S_loss: 0.0128 - val_detector_f1: 0.9317 - val_picker_P_f1: 0.5021 - val_picker_S_f1: 1.8011e-04

Epoch 00001: val_loss improved from inf to 0.02160, saving model to /Users/jun/phasepick/test_trainer_up_outputs/models/test_trainer_up_001.h5
Epoch 2/10
Learning rate:  0.001
3586/3586 [==============================] - 1701s 474ms/step - loss: 0.0177 - detector_loss: 0.1291 - picker_P_loss: 0.0080 - picker_S_loss: 0.0134 - detector_f1: 0.9414 - picker_P_f1: 0.3452 - picker_S_f1: 0.0679 - val_loss: 0.0145 - val_detector_loss: 0.0797 - val_picker_P_loss: 0.0054 - val_picker_S_loss: 0.0118 - val_detector_f1: 0.9674 - val_picker_P_f1: 0.5283 - val_picker_S_f1: 0.1267

Epoch 00002: val_loss 

In [2]:
dir(eqt.picker)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [3]:
from EQTransformer.core.tester import tester
# test.hdf5', input_csv='training_PandS.csv'
# tester(input_hdf5='test.hdf5', input_testset='test_trainer_outputs/test.npy', input_model='test_trainer_outputs/models/test_trainer_005.h5', output_name='test_tester', detection_threshold=0.20, P_threshold=0.1, S_threshold=0.1, number_of_plots=30, estimate_uncertainty=True, number_of_sampling=5, input_dimention=(9000, 3), normalization_mode='std', mode='generator', batch_size=10, gpuid=None, gpu_limit=None)
tester(input_hdf5='test.hdf5', input_testset='test_trainer_up_outputs/test.npy', input_model='test_trainer_up_outputs/models/test_trainer_up_002.h5', output_name='test_tester_up', detection_threshold=0.20, P_threshold=0.1, S_threshold=0.1, number_of_plots=30, estimate_uncertainty=True, number_of_sampling=5, input_dimention=(6000, 3), normalization_mode='std', mode='generator', batch_size=10, gpuid=None, gpu_limit=None)

Loading the model ...
Loading is complete!
Testing ...
Writting results into: " test_tester_up_outputs "


100%|██████████| 1196/1196 [11:29<00:00,  1.78it/s]

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure(figsize=(8,4))
plt.subplot(121)
# pred = pd.read_csv('test_tester_outputs/X_test_results.csv')
pred = pd.read_csv('test_tester_up_outputs/X_test_results.csv')
plt.hist(pred['P_error']/4, bins=np.arange(-20,20))
plt.xlabel('P error (s)')
plt.subplot(122)
plt.hist(pred['S_error']/4, bins=np.arange(-20,20))
plt.xlabel('S error (s)')
plt.show()

In [25]:
(pred['P_error'].where(np.abs(pred['P_error']/4)<20)/4).describe()

count    11942.000000
mean         0.033516
std          1.970352
min         -8.000000
25%         -1.000000
50%          0.000000
75%          1.000000
max         19.000000
Name: P_error, dtype: float64

In [22]:
(pred['S_error'].where(np.abs(pred['S_error']/4)<20)/4).describe()

count    8943.000000
mean        0.031058
std         4.913254
min       -19.750000
25%        -1.750000
50%         0.250000
75%         2.250000
max        19.250000
Name: S_error, dtype: float64

In [6]:
import seisbench as sb
import seisbench.data as sbd
data = sbd.DummyDataset()

In [12]:
data.get_waveforms(0)

array([[  34.,   47.,   51., ...,  667.,  695.,  662.],
       [-100.,  -99.,  -98., ..., -229., -208., -201.],
       [ 645.,  636.,  625., ...,  420.,  416.,  374.]])

In [ ]:
import h5py
with h5py.File('/Users/jun/phasepick/test.hdf5','w+') as f:
    

In [4]:
import h5py
f = h5py.File('/Users/jun/phasepick/EQTransformer/ModelsAndSampleData/100samples.hdf5','r')
# print(dir(f['data/109C.TA_20060723155859_EV']))
# print(dir(f))
# dset = f['data/109C.TA_20060723155859_EV']
print(dset[...])
f.close

[[-0.         -0.          0.        ]
 [-0.0085106  -0.03259867  0.00775105]
 [-0.02285321 -0.07897092  0.02457174]
 ...
 [ 0.10581018 -0.12264204 -0.062743  ]
 [ 0.00339233 -0.05204263 -0.01183952]
 [-0.         -0.         -0.        ]]


<bound method File.close of <HDF5 file "100samples.hdf5" (mode r)>>

In [15]:
import pandas as pd
csv = pd.read_csv('/Users/jun/phasepick/EQTransformer/ModelsAndSampleData/100samples.csv')
csv

network_code receiver_code receiver_type  receiver_latitude  \
0            TA          109C            BH            32.8889   
1            TA          109C            BH            32.8889   
2            TA          109C            BH            32.8889   
3            TA          109C            BH            32.8889   
4            TA          109C            BH            32.8889   
..          ...           ...           ...                ...   
95           TA          109C            BH            32.8889   
96           TA          109C            BH            32.8889   
97           TA          109C            BH            32.8889   
98           TA          109C            BH            32.8889   
99           TA          109C            BH            32.8889   

    receiver_longitude  receiver_elevation_m  p_arrival_sample p_status  \
0            -117.1051                 150.0             700.0   manual   
1            -117.1051                 150.0             600.0   manual   
2            -117.1051                 150.0             500.0   manual   
3            -117.1051                 150.0             900.0   manual   
4            -117.1051                 150.0             700.0   manual   
..                 ...                   ...               ...      ...   
95           -117.1051                 150.0             500.0   manual   
96           -117.1051                 150.0             500.0   manual   
97           -117.1051                 150.0             600.0   manual   
98           -117.1051                 150.0             400.0   manual   
99           -117.1051                 150.0             900.0   manual   

    p_weight  p_travel_sec  ...  source_magnitude_author  \
0       0.50     17.080000  ...                     None   
1       0.50     16.879999  ...                     None   
2       0.50     17.260000  ...                     None   
3       0.50     17.280001  ...                     None   
4       0.50     18.139999  ...                     None   
..       ...           ...  ...                      ...   
95      0.58      4.130000  ...                       CI   
96      0.58      8.910000  ...                       CI   
97      0.53     15.220000  ...                       CI   
98      0.61     15.120000  ...                       CI   
99      0.64     12.910000  ...                       CI   

   source_mechanism_strike_dip_rake  source_distance_deg source_distance_km  \
0                              None               0.9200             102.09   
1                              None               0.9100             101.34   
2                              None               0.9200             101.87   
3                              None               0.9300             103.26   
4                              None               0.9200             102.48   
..                              ...                  ...                ...   
95                             None               0.2089              23.23   
96                             None               0.4792              53.29   
97                             None               0.8566              95.26   
98                             None               0.8464              94.12   
99                             None               0.7045              78.35   

   back_azimuth_deg                                    snr_db  \
0             159.3  [ 56.79999924  55.40000153  47.40000153]   
1             281.7  [ 65.          65.5         61.40000153]   
2             280.5  [ 37.20000076  42.          38.59999847]   
3             281.6  [ 54.09999847  54.90000153  45.5       ]   
4               4.7  [ 58.20000076  56.20000076  53.79999924]   
..              ...                                       ...   
95            240.1  [ 17.39999962  15.80000019  12.80000019]   
96             28.2  [ 27.29999924  28.          31.89999962]   
97             21.2  [ 20.39999962  20.89999962  12.80

In [51]:
import h5py
f = h5py.File('/Users/jun/phasepick/EQTransformer/ModelsAndSampleData/EqT_model.h5','r')
# list(f.keys())
f['model_weights'].keys()
# f['optimizer_weights'].keys()
# dset = f['data/109C.TA_20060723155859_EV']
# dset[...]

<KeysViewHDF5 ['activation_1', 'activation_10', 'activation_11', 'activation_12', 'activation_13', 'activation_14', 'activation_2', 'activation_3', 'activation_4', 'activation_5', 'activation_6', 'activation_7', 'activation_8', 'activation_9', 'add_1', 'add_10', 'add_11', 'add_2', 'add_3', 'add_4', 'add_5', 'add_6', 'add_7', 'add_8', 'add_9', 'attentionD', 'attentionD0', 'attentionP', 'attentionS', 'batch_normalization_1', 'batch_normalization_10', 'batch_normalization_11', 'batch_normalization_12', 'batch_normalization_13', 'batch_normalization_14', 'batch_normalization_15', 'batch_normalization_16', 'batch_normalization_17', 'batch_normalization_2', 'batch_normalization_3', 'batch_normalization_4', 'batch_normalization_5', 'batch_normalization_6', 'batch_normalization_7', 'batch_normalization_8', 'batch_normalization_9', 'bidirectional_1', 'bidirectional_2', 'bidirectional_3', 'conv1d_1', 'conv1d_10', 'conv1d_11', 'conv1d_12', 'conv1d_13', 'conv1d_14', 'conv1d_15', 'conv1d_16', 'conv

In [26]:
class Test():
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def _getx(self):
        return self.x
    def _xaddy(self):
        x = self._getx()
        # x += self.y
        x.__add__(self.y)
        print(id(x))
        print(id(self.x))
        # x = .__add__(self.y)
        return self.x

testaa = Test(5,11)._xaddy()
testaa

4425894320
4425894320


5